### PR TITLE
GeoJson Parsing and Calculations

### PR DESCRIPTION
**Pull request by AntoineDao**
geojson area and perimeter calculation test setup. I wanted to try a bit of Test Driven Development so have written a bunch of tests and setup code to write geojson area/perimeter calculation methods. This is to help @EnricoBH get started if he's keen. (no worries if not I'm sure Chris, myself or someone else will happily pick it up if it needs to be urgently fixed!).

Otherwise I reckon this would take a starter a solid afternoon to crack.

This relates to #17

### CODE REVIEW

**Comment by chriswmackey** [comment]
@AntoineDao ,

I don't think that we'll add in the geojson capabilities until I have taken care of this issue first, which will add objects that actually store the floor curves:
https://github.com/ladybug-tools/dragonfly/issues/10

And I think that we will use ladybug-geometry to compute the areas of the geojson polygons, probably using a formula like this:
https://www.mathopenref.com/coordpolygonarea.html

We can leave the PR here for now but I just wanted to you be aware that it may be some time before we can merge this in.

**Comment by saeranv** [comment]
@AntoineDao @chriswmackey 

Super trivial point here, that you guys might already know: the area of a polygon in that mathopenref.com link is actually just the long form of a simpler formula: area of any convex geometry = sum(magnitude of cross product of vertices) / 2. 

Because the magnitude of the cross product of two vectors is equal to the area of a parallelogram defined by the two vectors. If we divide the scalar cross product by two to get the area of the triangle, and then add up all the geometries that make up a convex geometry, we get the total area. 

image

Using the cross product is better then that specific formula, because it works in 2 and 3 dimensions, and promotes code reuse!

S

**Comment by chriswmackey** [comment]
Good to know @saeranv ,
For clarification, does your cross product formula not give the correct result for concave polygons?  I see that the original formula that I posted works for both concave and convex polygons.

**Comment by saeranv** [comment]
You're absolutely right @chriswmackey. 

I thought, intuitively, that concave polygons wouldn't work, since it would create overlapping "triangles" that wouldn't sum to the total area. However I just tested it out, and it works out. Because the area derived from cross product will be positive or negative (based on direction of normal) which will cancel out weird overlaps and give us the correct total area.

**Comment by chriswmackey** [comment]
@saeranv and @AntoineDao ,

I am just letting you know that I have implemented @saeranv 's  method as part of [this pull request to the Ladybug Geometry library](https://github.com/ladybug-tools/ladybug-geometry/pull/3).  In particular the [Polygon2D class](https://github.com/ladybug-tools/ladybug-geometry/pull/3/files#diff-86784ee6cd82e31df5eff430a8f21305) carries these specific methods and also uses them to get whether the points are clockwise or counter-clockwise (super-useful formula, @saeranv !).  This should hopefully make these methods accessible to all of the other libraries and, once I finish writing some tests for the geomtry library, I will begin using them here in DF.

**Comment by AntoineDao** [comment]
I'll close this issue as it's ancient and most likely won't work with the current iteration of dragonfly.

**Comment by chriswmackey** [comment]
Thanks @AntoineDao . Dragonfly-core is now ready for someone to implement `from_geojson` classmethods , which I have come to realize is the "correct way" support this within this repo . I opened an issue over there and referenced this old PR since I think we can reuse some of the code here (at least the test files) when we implement it.
https://github.com/ladybug-tools/dragonfly-core/issues/40

**Pull request closed without merging**
